### ISSUE TITLE
Official release compatible with NVDA 2021.1

### ISSUE THREAD

**Issue by lukaszgo1** [ABuffEr/noBeepsSpeechMode#3]
Hello @ABuffEr Would it be possible to officially release version 5.0 and open a PR against add-on files to have it updated on the add-ons website? A lot of people seems to want to have this add-on compatible with 2021.1 and for less advanced users going to gitHub and looking in the readme for a link to the release is a no go. Also if I may suggest something would it be possible for you to use GitHub releases and attach add-on files to them as an artifact so that links are permanent and not depended on a given file being kept in the `packages` folder. With that strategy you would be able to get rid of this directory completely and create two releases: one for 4.0 and one for 5.0 and link to their artifacts from the readme.

**Comment by ABuffEr** [comment]
Hi @lukaszgo1 ,
all done! :)
See PR [#141](https://github.com/nvaccess/addonFiles/pull/141) and [#142](https://github.com/nvaccess/addonFiles/pull/142) on nvaccess/addonFiles
