### ISSUE TITLE
Suggestion: Note that this functionality is now built in.

### ISSUE THREAD

**Issue by xtremeranger** [ABuffEr/noBeepsSpeechMode#6]
It would be helpful to note that removal of this add-on in 2024.1 is because there is now a setting built in to toggle this.  Something like: "2024.1 has a setting to control which modes are part of the Cycle Speech Mode command https://www.nvaccess.org/files/nvda/documentation/userGuide.html#SpeechModesDisabling"

**Comment by ABuffEr** [comment]
Hi,
if you install/update the latest version from store, after NVDA restart you should get a warning that says:
"NoBeepsSpeechMode is no longer necessary for NVDA after 2023.3,
and may conflict with the new speech modes feature; please remove it."
You suggest to include a link to documentation, sure, and you're right, it would have been a good idea. But I have no intention to release a new build for this, sorry.

**Comment by xtremeranger** [comment]
Thanks.  I don't remember seeing that, only that it was disabled by NVDA.  But maybe I did see it and just didn't understand.  Either way, thanks for the reply, and I understand not wanting to make another release, I was just thinking it would be added to the README.
